// ============================================================
// PLAN TRENINGOWY — podmienialny plik wejściowy aplikacji.
// Źródło: "Plan treningowy 20 minut.md" (2026-06-12).
// Żeby zmienić plan: wygeneruj nowy obiekt PLAN z pliku .md
// i podmień ten plik. Historia w CSV pozostaje kompatybilna,
// dopóki nazwy ćwiczeń się zgadzają.
// ============================================================

const PLAN = {
  version: "2026-06-12.2",
  csvHeader: "data,sesja,cwiczenie,ciezar,powt1,powt2,powt3,rpe,uwagi",
  sessions: [
    {
      id: "A",
      title: "Klatka, plecy poziomo, nogi",
      station: "ławka + hantle, leg press",
      exercises: [
        { slot: "A1", name: "FLAT DB PRESS", sets: 2, repMin: 8, repMax: 10, rpe: "8–9", inc: 2.5,
          subs: ["MACHINE CHEST PRESS", "WEIGHTED DIP"],
          tip: "Pełny zakres, kontrolowane opuszczanie" },
        { slot: "A2", name: "INCLINE CHEST-SUPPORTED DB ROW", sets: 2, repMin: 8, repMax: 10, rpe: "8–9", inc: 2.5,
          subs: ["1-ARM DB ROW", "SEATED CABLE ROW"],
          tip: "Łokcie ~30°, ściągaj łopatki" },
        { slot: "B1", name: "LEG PRESS", sets: 2, repMin: 10, repMax: 12, rpe: "8–9", inc: 5,
          subs: ["HACK SQUAT", "GOBLET SQUAT"],
          tip: "Stopy na średniej szerokości, nie blokuj kolan" },
        { slot: "B2", name: "LEG PRESS TOE PRESS", sets: 2, repMin: 12, repMax: 15, rpe: "9–10", inc: 5,
          subs: ["SEATED CALF RAISE", "STANDING CALF RAISE"],
          tip: "Pełne rozciągnięcie na dole, bez odbicia" },
      ],
      mobility: [
        "Rozciąganie zginaczy bioder w półklęku 2×30 s/str.",
        "Rozciąganie klatki o słupek 2×30 s",
        "Dead bug 2×10",
      ],
    },
    {
      id: "B",
      title: "Zawias, barki, plecy pionowo",
      station: "ławka + hantle, wieża wyciągu",
      exercises: [
        { slot: "A1", name: "DB ROMANIAN DEADLIFT", sets: 2, repMin: 8, repMax: 10, rpe: "8–9", inc: 2.5,
          subs: ["ROMANIAN DEADLIFT", "45' HYPEREXTENSION"],
          tip: "Neutralne plecy, biodra w tył, czuj dwugłowe" },
        { slot: "A2", name: "SEATED DB SHOULDER PRESS", sets: 2, repMin: 8, repMax: 10, rpe: "8–9", inc: 2.5,
          subs: ["MACHINE SHOULDER PRESS", "STANDING DB ARNOLD PRESS"],
          tip: "Nie zatrzymuj się na dole" },
        { slot: "B1", name: "LAT PULLDOWN", sets: 2, repMin: 10, repMax: 12, rpe: "8–9", inc: 2.5,
          subs: ["NEUTRAL-GRIP PULLDOWN", "2-GRIP PULL-UP"],
          tip: "Łokcie w dół i do środka, bez bujania" },
        { slot: "B2", name: "ROPE FACEPULL", sets: 2, repMin: 12, repMax: 15, rpe: "9–10", inc: 2.5,
          subs: ["CABLE LATERAL RAISE", "REVERSE PEC DECK"],
          tip: "Ciągnij „na zewnątrz”; co kilka sesji wymieniaj z zamiennikiem 1" },
      ],
      mobility: [
        "Rozciąganie dwugłowych 2×30 s/str.",
        "Rotacje piersiowe „open book” 2×8/str.",
        "Plank 2×30 s",
      ],
    },
    {
      id: "C",
      title: "Uda izolacyjnie, ramiona",
      station: "sąsiednie maszyny nóg, gryf EZ",
      exercises: [
        { slot: "A1", name: "LEG EXTENSION", sets: 2, repMin: 12, repMax: 15, rpe: "9–10", inc: 5,
          subs: ["DB STEP UP", "GOBLET SQUAT"],
          tip: "Sekunda zatrzymania na górze" },
        { slot: "A2", name: "SEATED LEG CURL", sets: 2, repMin: 10, repMax: 12, rpe: "9–10", inc: 5,
          subs: ["LYING LEG CURL", "NORDIC HAM CURL"],
          tip: "Biodra dociśnięte, pełny zakres" },
        { slot: "B1", name: "EZ BAR CURL", sets: 2, repMin: 10, repMax: 12, rpe: "9–10", inc: 2.5,
          subs: ["DB CURL", "CABLE EZ CURL"],
          tip: "Łuk „na zewnątrz”, nie „do góry”" },
        { slot: "B2", name: "EZ BAR SKULL CRUSHER", sets: 2, repMin: 12, repMax: 15, rpe: "9–10", inc: 2.5,
          subs: ["OVERHEAD CABLE TRICEPS EXTENSION", "DB FRENCH PRESS"],
          tip: "Gryf za głowę, stałe napięcie tricepsa" },
      ],
      mobility: [
        "Couch stretch 2×30 s/str.",
        "Krążenia ramion z kijem/gumą 2×10",
        "Cat-cow ×8",
      ],
    },
  ],
};

// Opisy techniki + filmy instruktażowe (YouTube, ~1–2 min).
// Obrazki w aplikacji to 3 klatki z danego filmu (i.ytimg.com/vi/<yt>/hq1..3.jpg).
// Linki zweryfikowane 2026-06-12.
const EXERCISE_INFO = {
  "FLAT DB PRESS": { yt: "VmB1G1K7v94",
    desc: "Leżąc płasko na ławce, opuść hantle do boków klatki z łokciami pod kątem ~45° i wyciśnij w górę nad mostek. Łopatki ściągnięte, pełny zakres na dole." },
  "INCLINE CHEST-SUPPORTED DB ROW": { yt: "vmX58YYK3-8",
    desc: "Klatka oparta o ławkę skośną, hantle zwisają swobodnie. Wiosłuj z łokciami ~30° od tułowia, ściągając łopatki na górze." },
  "LEG PRESS": { yt: "8EMbB0tCn7Q",
    desc: "Stopy na środku platformy na szerokość bioder. Opuść platformę głęboko, nie odrywając dolnych pleców od oparcia; wypchnij bez blokowania kolan." },
  "LEG PRESS TOE PRESS": { yt: "M4FojyRAcuE",
    desc: "Palce stóp na dolnej krawędzi platformy, pięty poza nią. Wypchnij samymi palcami; na dole pełne rozciągnięcie łydki, bez odbijania." },
  "DB ROMANIAN DEADLIFT": { yt: "FQKfr1YDhEk",
    desc: "Hantle przy udach, kolana lekko ugięte. Pchnij biodra w tył i opuszczaj hantle wzdłuż nóg do mocnego rozciągnięcia dwugłowych; wróć napinając pośladki." },
  "SEATED DB SHOULDER PRESS": { yt: "GFblCmuEE18",
    desc: "Siedząc z podpartymi plecami wyciskaj hantle z wysokości uszu nad głowę. Kontroluj opuszczanie, nie zatrzymuj się na dole." },
  "LAT PULLDOWN": { yt: "qMLOzlpHvDk",
    desc: "Chwyt nieco szerzej niż barki. Ciągnij drążek do górnej części klatki, prowadząc łokcie w dół i do tułowia; bez bujania tułowiem." },
  "ROPE FACEPULL": { yt: "wnPX6Fwe-Fg",
    desc: "Lina na wysokości twarzy. Ciągnij końce liny do uszu, rozchylając je na zewnątrz — czujesz tył barków i mięśnie między łopatkami." },
  "LEG EXTENSION": { yt: "YyvSfVjQeL0",
    desc: "Ustaw oparcie tak, by kolana licowały z osią maszyny. Wyprostuj nogi do pełna, sekunda zatrzymania na górze, powolne opuszczanie." },
  "SEATED LEG CURL": { yt: "ELOCsoDSmrg",
    desc: "Uda dociśnięte do siedziska, wałek nad piętami. Zegnij kolana do pełna i wróć powoli, nie odrywając bioder." },
  "EZ BAR CURL": { yt: "6LrOTcr595A",
    desc: "Podchwyt na skosach gryfu EZ, łokcie przy tułowiu. Uginaj ramiona łukiem „na zewnątrz”, bez bujania tułowiem." },
  "EZ BAR SKULL CRUSHER": { yt: "d_KZxkY_0cM",
    desc: "Leżąc, opuszczaj gryf łukiem za głowę (nie do czoła), łokcie nieruchomo. Prostuj ramiona, utrzymując stałe napięcie tricepsów." },
  "MACHINE CHEST PRESS": { yt: "sqNwDkUU_Ps",
    desc: "Uchwyty na wysokości środka klatki, łopatki ściągnięte. Wyciśnij do prawie pełnego wyprostu i wróć powoli, czując rozciągnięcie klatki." },
  "WEIGHTED DIP": { yt: "2i3o0bFZT_s",
    desc: "Na poręczach, łokcie ~45° od tułowia, tors lekko pochylony. Opuść się do rozciągnięcia klatki i wypchnij bez blokowania łokci." },
  "1-ARM DB ROW": { yt: "pYcpY20QaE8",
    desc: "Kolano i dłoń na ławce, plecy proste. Wiosłuj hantlem do biodra z łokciem przy tułowiu; nie rotuj tułowia." },
  "SEATED CABLE ROW": { yt: "GZbfZ033f74",
    desc: "Siad z lekko ugiętymi kolanami, plecy neutralne. Ciągnij uchwyt do brzucha, ściągając łopatki; wracaj do pełnego rozciągnięcia ramion." },
  "HACK SQUAT": { yt: "0tn5K9NlCfo",
    desc: "Stopy wysoko i szeroko na platformie, plecy dociśnięte do oparcia. Zjedź głęboko i wstań; kolana w linii palców stóp." },
  "GOBLET SQUAT": { yt: "hFD8CIQM3GU",
    desc: "Hantel trzymany pionowo pod brodą. Usiądź głęboko między kolana z prostymi plecami; łokcie schodzą między kolana." },
  "SEATED CALF RAISE": { yt: "BxfKOyI8sUg",
    desc: "Wałek na udach, palce na podeście. Unieś pięty maksymalnie wysoko; na dole pełne rozciągnięcie, bez odbijania." },
  "STANDING CALF RAISE": { yt: "30ygzcJw4v4",
    desc: "Wyprostowana sylwetka, palce na podeście. Pełne wspięcie na palce, potem powolny zjazd piętami poniżej poziomu podestu." },
  "ROMANIAN DEADLIFT": { yt: "7j-2w4-P14I",
    desc: "Sztanga przy udach. Biodra w tył, plecy neutralne — opuszczaj gryf wzdłuż nóg do rozciągnięcia dwugłowych i wróć siłą pośladków." },
  "45' HYPEREXTENSION": { yt: "7KXsFvooId0",
    desc: "Biodra na poduszce ławki 45°. Opuść tułów i unieś do linii prostej z nogami siłą pośladków i dwugłowych; bez przeprostu pleców." },
  "MACHINE SHOULDER PRESS": { yt: "Wqq43dKW1TU",
    desc: "Siedząc, uchwyty na wysokości uszu, plecy dociśnięte do oparcia. Wyciśnij nad głowę i opuść kontrolowanie." },
  "STANDING DB ARNOLD PRESS": { yt: "6Z15_WdXmVw",
    desc: "Start z hantlami przed sobą podchwytem; podczas wyciskania rotuj dłonie na zewnątrz, kończąc nachwytem nad głową." },
  "NEUTRAL-GRIP PULLDOWN": { yt: "aoHXhJ2x2BQ",
    desc: "Uchwyt równoległy (dłonie do siebie). Ciągnij do górnej klatki, łokcie do żeber; mocne rozciągnięcie ramion na górze." },
  "2-GRIP PULL-UP": { yt: "XB_7En-zf_M",
    desc: "Pierwsza seria szeroko nachwytem (~1,5× barki), druga podchwytem na szerokość barków. Pełny zwis na dole, broda nad drążek." },
  "CABLE LATERAL RAISE": { yt: "qitQHqNZbeM",
    desc: "Linka prowadzona za plecami lub z boku, lekki odchył od wieży. Unoś ramię „na zewnątrz” do poziomu barku; mały ciężar, czysta technika." },
  "REVERSE PEC DECK": { yt: "RAir7uJzzu0",
    desc: "Siad twarzą do oparcia, uchwyty przed sobą. Prowadź ramiona łukiem w tył, „na zewnątrz” — czujesz tył barków." },
  "DB STEP UP": { yt: "9ZknEYboBOQ",
    desc: "Wejdź na podest całą stopą i wstań siłą nogi na podeście (bez odbicia z dołu); zejdź kontrolowanie." },
  "LYING LEG CURL": { yt: "1Tq3QdYUuHs",
    desc: "Leżąc na brzuchu, biodra dociśnięte do ławki. Dociągnij wałek do pośladków i wróć powoli." },
  "NORDIC HAM CURL": { yt: "3-4pKUhkzoQ",
    desc: "Kolana na podkładce, stopy zablokowane. Opuszczaj tułów do przodu jak najwolniej, hamując dwugłowymi; przy powrocie pomóż sobie rękami." },
  "DB CURL": { yt: "sAq_ocpRh_I",
    desc: "Hantle wzdłuż tułowia. Uginaj z supinacją nadgarstka, łokcie nieruchomo przy żebrach." },
  "CABLE EZ CURL": { yt: "AsAVbj7puKo",
    desc: "Gryf EZ na dolnym wyciągu. Stałe napięcie w całym zakresie; łokcie przy tułowiu, bez bujania." },
  "OVERHEAD CABLE TRICEPS EXTENSION": { yt: "ns-RGsbzqok",
    desc: "Plecami do wyciągu, lina za głową. Prostuj ramiona nad głową do pełna; łokcie wąsko, mocne rozciągnięcie tricepsa na dole." },
  "DB FRENCH PRESS": { yt: "LM8ahUmGnOQ",
    desc: "Jeden hantel trzymany oburącz nad głową. Opuść za głowę, zginając łokcie blisko głowy, i wyprostuj ramiona do pełna." },
};

// Opisy + filmy dla ćwiczeń mobilności. Klucz = dokładny tekst z PLAN.sessions[].mobility.
// Filmy: kandydaci z tools/find_mobility.py (krótkie, wiarygodne kanały) — łatwe do podmiany.
const MOBILITY_INFO = {
  "Rozciąganie zginaczy bioder w półklęku 2×30 s/str.": { yt: "iZ1eZBY4fwM",
    desc: "Klęk na jednym kolanie (miękkie podłoże pod kolanem), druga noga z przodu zgięta ~90°. Napnij pośladek nogi klęczącej i delikatnie przesuń biodra w przód — rozciąganie z przodu biodra. Tułów pionowo, bez wyginania lędźwi." },
  "Rozciąganie klatki o słupek 2×30 s": { yt: "CEQMx4zFwYs",
    desc: "Przedramię oprzyj o framugę/słupek, łokieć na wysokości barku (~90°). Zrób mały krok w przód i delikatnie obróć tułów w drugą stronę — czujesz rozciąganie przedniej części klatki i barku. Nie wzruszaj barku do ucha." },
  "Dead bug 2×10": { yt: "o4GKiEoYClI",
    desc: "Leż na plecach, ręce nad barkami, biodra i kolana zgięte 90°, lędźwie dociśnięte do podłogi. Powoli opuszczaj przeciwległą rękę i nogę prawie do wyprostu bez odrywania pleców; wróć i zmień stronę. Spokojny oddech." },
  "Rozciąganie dwugłowych 2×30 s/str.": { yt: "LVY692zJK0A",
    desc: "Jedna pięta z przodu na podłodze, palce w górę, kolano lekko ugięte. Odprowadź biodra w tył (jak ukłon) z prostymi plecami i pochyl się od bioder, aż poczujesz rozciąganie z tyłu uda. Nie zaokrąglaj pleców." },
  "Rotacje piersiowe „open book” 2×8/str.": { yt: "YMswmjk7Qj4",
    desc: "Leż na boku, biodra i kolana zgięte 90°, ręce wyprostowane przed sobą złożone razem. Górną ręką „otwórz książkę” — prowadź ją łukiem na drugą stronę, wzrok za dłonią, aż łopatka dotknie podłogi. Ruch z klatki, biodra nieruchome." },
  "Plank 2×30 s": { yt: "pSHjTRCQxIw",
    desc: "Podpór na przedramionach, łokcie pod barkami. Ciało w linii prostej od głowy do pięt — napnij brzuch i pośladki, miednica lekko podwinięta (bez opadania bioder). Naturalny oddech, kark wydłużony." },
  "Couch stretch 2×30 s/str.": { yt: "Fg-lwNBzVV8",
    desc: "Klęk tyłem do ściany/ławki; piszczel nogi z tyłu oprzyj o ścianę, kolano nisko, druga noga z przodu w wykroku. Napnij pośladek i wyprostuj tułów — mocne rozciąganie przodu uda i biodra. Zaczynaj łagodnie, lędźwie neutralne." },
  "Krążenia ramion z kijem/gumą 2×10": { yt: "vQjlYoZCz50",
    desc: "Chwyć kij lub gumę szeroko nachwytem przed sobą. Z wyprostowanymi łokciami prowadź drążek łukiem nad głowę i za plecy, potem z powrotem — płynnie, bez bólu. Węższy chwyt = trudniej; dobierz szerokość tak, by ruch był swobodny." },
  "Cat-cow ×8": { yt: "u5TglXNBrtE",
    desc: "Klęk podparty, dłonie pod barkami, kolana pod biodrami. Wdech — ugnij plecy w dół, klatka i wzrok w górę (krowa). Wydech — zaokrąglij plecy w górę, broda do mostka (kot). Płynnie, w rytm oddechu, ruch z całego kręgosłupa." },
};
